### ISSUE TITLE
Doubt regarding pyrem

### ISSUE THREAD

**Issue by ManiSravaniKothapalli** [emichael/PyREM#13]
Hi

I have installed pyrem package in python and used the below format
pyrem.univariate.ap_entropy(a, m, R)
But it is showing that 'there is no attribute named univariate'
Please help me with this
Or is there any alternative to calculate approximate entropy
Please explain in detail

**Comment by emichael** [comment]
I think you've got the wrong PyREM.

**Comment by ManiSravaniKothapalli** [comment]
Wrong pyrem in the sense?
Can you help me with this ?
